# Generated by Django 2.2.1 on 2019-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
            ],
        ),
    ]
