# Generated by Django 2.2.1 on 2019-05-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
    ]
